### ISSUE TITLE
simple format change

### ISSUE THREAD

**Issue by kaichop** [WangGenomicsLab/SeqMule#32] opened 2015-01-10 05:51 UTC
The format below is confusing, because of empty paragraphs above and below it. Most people would think that it refers to one step, but in fact this is not.

----------NOTICE----------
[ => SeqMule Execution Status: step 14 is finished at Fri Jan  9 21:28:47 PST 2015, Remove temporary files, 0.0 min]
[ => SeqMule Execution Status: Running 15 of 15 steps: Generating html report
Time Elapsed: 3 hr 4 min 0 s]
Assume all results of each individual sample are put in a single folder
SeqMule reports saved to snap-freebayes_report

It should be changed to something like below:

[ => SeqMule Execution Status: step 14 is finished at Fri Jan  9 21:28:47 PST 2015, Remove temporary files, 0.0 min]

----------NOTICE----------
[ => SeqMule Execution Status: Running 15 of 15 steps: Generating html report
Time Elapsed: 3 hr 4 min 0 s]
Assume all results of each individual sample are put in a single folder
SeqMule reports saved to snap-freebayes_report

Finally, at the beginning of the output, users should see a line similar to below to know the actual time (because before step 1, it actually takes a lot of time to do pre-processing such as converting phred64 to phred33, etc):

NOTICE: Parsing global settings...
Done

-----------NOTICE------------------
[ => SeqMule Execution Status: start pre-processing of data at Fri Jan  9 21:28:47 PST 2015]
Checking Phred score scheme: snap-freebayes_result/snap-freebayes.1.fastq snap-freebayes_result/snap-freebayes.2.fastq

**Comment by yunfeiguo** [comment] 2015-01-11 02:13
1. position of "----------NOTICE----------" has been adjusted. Thanks!
2. converting phred64 to phred33 (if necessary) is done as step1 rather than pre-processing. I try to avoid any time-consuming preprocessing before step1. Right now there should not be any time-consuming process before step 1. If you found one, please let me know. Thank you!

**Comment by kaichop** [comment] 2015-01-12 08:40
I mean to just print out a NOTICE message so that people know the time.

Right now, I want to know how much time it takes to analyze one genome, but I cannot see the 'start time' and only the 'finish time' for the last step.

**Comment by yunfeiguo** [comment] 2015-01-14 00:35
Thanks!

I will make the starting and finishing NOTICE messages of the same
step look like one block, with time stamp, time consumption info, clearly
separated from other steps.

I will add a timestamp at the very beginning.

**Comment by yunfeiguo** [comment] 2015-01-14 00:53
```
*************EXECUTION BEGINS at Tue Jan 13 16:47:08 PST 2015*****************

----------NOTICE----------
[ => SeqMule Execution Status: Running 1 of 16 steps: Convert phred64 to phred33
at Tue Jan 13 16:47:09 PST 2015, Time Elapsed: 0 hr 0 min 1 s]
NOTICE: Counting non-empty lines in part_result/part.1.fastq
Begin converting part_result/part.1.fastq to standard Phred score
Done
[ => SeqMule Execution Status: step 1 is finished at Tue Jan 13 16:47:14 PST 2015, Convert phred64 to phred33, 0.1 min]


----------NOTICE----------
[ => SeqMule Execution Status: Running 2 of 16 steps: Convert phred64 to phred33
at Tue Jan 13 16:47:14 PST 2015, Time Elapsed: 0 hr 0 min 6 s]
```
The end becomes (the timestamp at the very end is removed as it's duplicate of the 2nd last line).
```
----------NOTICE----------
[ => SeqMule Execution Status: Running 16 of 16 steps: Generating html report
at Tue Jan 13 16:48:44 PST 2015, Time Elapsed: 0 hr 1 min 36 s]
Assume all results of each individual sample are put in a single folder
SeqMule reports saved to part_report
[ => SeqMule Execution Status: step 16 is finished at Tue Jan 13 16:48:48 PST 2015, Generating html report, 0.1 min]

[ => SeqMule Execution Status: All done at Tue Jan 13 16:48:48 PST 2015]
Total time: 0 hr 1 min 40 s
```

**Closed** 2015-02-13 17:21 UTC
